export const DEFAULT_LOCALE = 'english'
export const SUPPORTED_LOCALES = [ 'english', 'french' ]
export const DEFAULT_LANGUAGE = 'en'
export const LANGUAGE_MAPPINGS = {
    english: 'en',
    french: 'fr'
}
export const UNITS = [
    {
        assistantKey: 'mm',
        apiKey: 'mm'
    },
    {
        assistantKey:'cm',
        apiKey:'cm'
    },
    {
        assistantKey:'m',
        apiKey:'m'
    },
    {
        assistantKey:'km',
        apiKey:'km'
    },
    {
        assistantKey:'in',
        apiKey:'in'
    },
    {
        assistantKey:'ft',
        apiKey:'ft'
    },
    {
        assistantKey:'mi',
        apiKey:'mi'
    },
    {
        assistantKey:'mm2',
        apiKey:'mm2'
    },
    {
        assistantKey:'cm2',
        apiKey:'cm2'
    },
    {
        assistantKey:'m2',
        apiKey:'m2'
    },
    {
        assistantKey:'km2',
        apiKey:'km2'
    },
    {
        assistantKey:'ha',
        apiKey:'ha'
    },
    {
        assistantKey:'in2',
        apiKey:'in2'
    },
    {
        assistantKey:'ft2',
        apiKey:'ft2'
    },
    {
        assistantKey:'mi2',
        apiKey:'mi2'
    },
    {
        assistantKey:'mcg',
        apiKey:'mg'
    },
    {
        assistantKey:'g',
        apiKey:'g'
    },
    {
        assistantKey:'kg',
        apiKey:'kg'
    },
    {
        assistantKey:'oz',
        apiKey:'oz'
    },
    {
        assistantKey:'lb',
        apiKey:'lb'
    },
    {
        assistantKey:'t',
        apiKey:'t'
    },
    {
        assistantKey:'mm3',
        apiKey:'mm3'
    },
    {
        assistantKey:'cm3',
        apiKey:'cm3'
    },
    {
        assistantKey:'m3',
        apiKey:'m3'
    },
    {
        assistantKey:'km3',
        apiKey:'km3'
    },
    {
        assistantKey:'in3',
        apiKey:'in3'
    },
    {
        assistantKey:'ft3',
        apiKey:'ft3'
    },
    {
        assistantKey:'yd3',
        apiKey:'yd3'
    },    
    {
        assistantKey:'ml',
        apiKey:'ml'
    },    
    {
        assistantKey:'cl',
        apiKey:'cl'
    },    
    {
        assistantKey:'l',
        apiKey:'l'
    },    
    {
        assistantKey:'kl',
        apiKey:'kl'
    },    
    {
        assistantKey:'tsp',
        apiKey:'tsp'
    },    
    {
        assistantKey:'tbsp',
        apiKey:'Tbs'
    },    
    {
        assistantKey:'fl-oz',
        apiKey:'fl-oz'
    },    
    {
        assistantKey:'cup',
        apiKey:'cup'
    },
    {
        assistantKey:'pt',
        apiKey:'pnt'
    },
    {
        assistantKey:'qt',
        apiKey:'qt'
    },
    {
        assistantKey:'gal',
        apiKey:'gal'
    },
    {
        assistantKey:'C',
        apiKey:'C'
    },
    {
        assistantKey:'F',
        apiKey:'F'
    },
    {
        assistantKey:'K',
        apiKey:'K'
    },
    {
        assistantKey:'ns',
        apiKey:'ns'
    },
    {
        assistantKey:'mu',
        apiKey:'mu'
    },
    {
        assistantKey:'ms',
        apiKey:'ms'
    },
    {
        assistantKey:'ms',
        apiKey:'ms'
    },
    {
        assistantKey:'s',
        apiKey:'s'
    },
    {
        assistantKey:'min',
        apiKey:'min'
    },
    {
        assistantKey:'h',
        apiKey:'h'
    },
    {
        assistantKey:'d',
        apiKey:'d'
    },
    {
        assistantKey:'week',
        apiKey:'week'
    },
    {
        assistantKey:'month',
        apiKey:'month'
    },
    {
        assistantKey:'year',
        apiKey:'year'
    },
    {
        assistantKey:'mm3/s',
        apiKey:'mm3/s'
    },
    {
        assistantKey:'cm3/s',
        apiKey:'cm3/s'
    },
    {
        assistantKey:'ml/s',
        apiKey:'ml/s'
    },
    {
        assistantKey:'cl/s',
        apiKey:'cl/s'
    },
    {
        assistantKey:'dl/s',
        apiKey:'dl/s'
    },
    {
        assistantKey:'l/s',
        apiKey:'l/s'
    },
    {
        assistantKey:'l/min',
        apiKey:'l/min'
    },
    {
        assistantKey:'l/h',
        apiKey:'l/h'
    },
    {
        assistantKey:'kl/s',
        apiKey:'kl/s'
    },
    {
        assistantKey:'kl/min',
        apiKey:'kl/min'
    },
    {
        assistantKey:'kl/h',
        apiKey:'kl/h'
    },
    {
        assistantKey:'m3/s',
        apiKey:'m3/s'
    },
    {
        assistantKey:'m3/min',
        apiKey:'m3/min'
    },
    {
        assistantKey:'m3/h',
        apiKey:'m3/h'
    },
    {
        assistantKey:'km3/s',
        apiKey:'km3/s'
    },
    {
        assistantKey:'in3/s',
        apiKey:'in3/s'
    },
    {
        assistantKey:'in3/min',
        apiKey:'in3/min'
    },
    {
        assistantKey:'in3/h',
        apiKey:'in3/h'
    },
    {
        assistantKey:'fl-oz/s',
        apiKey:'fl-oz/s'
    },
    {
        assistantKey:'fl-oz/min',
        apiKey:'fl-oz/min'
    },
    {
        assistantKey:'fl-oz/h',
        apiKey:'fl-oz/h'
    },
    {
        assistantKey:'ft3/s',
        apiKey:'ft3/s'
    },
    {
        assistantKey:'ft3/min',
        apiKey:'ft3/min'
    },
    {
        assistantKey:'ft3/h',
        apiKey:'ft3/h'
    },
    {
        assistantKey:'yd3/s',
        apiKey:'yd3/s'
    },
    {
        assistantKey:'yd3/min',
        apiKey:'yd3/min'
    },
    {
        assistantKey:'yd3/h',
        apiKey:'yd3/h'
    },
    {
        assistantKey:'m/s',
        apiKey:'m/s'
    },
    {
        assistantKey:'km/s',
        apiKey:'km/s'
    },
    {
        assistantKey:'mph',
        apiKey:'m/h'
    },
    {
        assistantKey:'knot',
        apiKey:'knot'
    },
    {
        assistantKey:'ft/s',
        apiKey:'ft/s'
    },
    {
        assistantKey:'Pa',
        apiKey:'Pa'
    },
    {
        assistantKey:'hPa',
        apiKey:'hPa'
    },
    {
        assistantKey:'kPa',
        apiKey:'kPa'
    },
    {
        assistantKey:'MPa',
        apiKey:'MPa'
    },
    {
        assistantKey:'bar',
        apiKey:'bar'
    },
    {
        assistantKey:'b',
        apiKey:'b'
    },
    {
        assistantKey:'Kb',
        apiKey:'Kb'
    },
    {
        assistantKey:'Mb',
        apiKey:'Mb'
    },
    {
        assistantKey:'Gb',
        apiKey:'Gb'
    },
    {
        assistantKey:'Gb',
        apiKey:'Tb'
    },
    {
        assistantKey:'B',
        apiKey:'B'
    },
    {
        assistantKey:'KB',
        apiKey:'KB'
    },
    {
        assistantKey:'MB',
        apiKey:'MB'
    },
    {
        assistantKey:'GB',
        apiKey:'GB'
    },
    {
        assistantKey:'TB',
        apiKey:'TB'
    },
    {
        assistantKey:'V',
        apiKey:'V'
    },
    {
        assistantKey:'mV',
        apiKey:'mV'
    },
    {
        assistantKey:'kV',
        apiKey:'kV'
    },
    {
        assistantKey:'A',
        apiKey:'A'
    },
    {
        assistantKey:'mA',
        apiKey:'mA'
    },
    {
        assistantKey:'kA',
        apiKey:'kA'
    }
]